//
// File generated by rootcint at Wed Aug 14 14:49:49 2013

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dOdIsrcdIg4lbneCint
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "g4lbneCint.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void TrackPoint_t_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_TrackPoint_t(void *p = 0);
   static void *newArray_TrackPoint_t(Long_t size, void *p);
   static void delete_TrackPoint_t(void *p);
   static void deleteArray_TrackPoint_t(void *p);
   static void destruct_TrackPoint_t(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::TrackPoint_t*)
   {
      ::TrackPoint_t *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TrackPoint_t >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TrackPoint_t", ::TrackPoint_t::Class_Version(), "./include/../include/TrackPoint_t.hh", 25,
                  typeid(::TrackPoint_t), DefineBehavior(ptr, ptr),
                  &::TrackPoint_t::Dictionary, isa_proxy, 4,
                  sizeof(::TrackPoint_t) );
      instance.SetNew(&new_TrackPoint_t);
      instance.SetNewArray(&newArray_TrackPoint_t);
      instance.SetDelete(&delete_TrackPoint_t);
      instance.SetDeleteArray(&deleteArray_TrackPoint_t);
      instance.SetDestructor(&destruct_TrackPoint_t);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::TrackPoint_t*)
   {
      return GenerateInitInstanceLocal((::TrackPoint_t*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TrackPoint_t*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

namespace TrkPoint {
   namespace ROOT {
      inline ::ROOT::TGenericClassInfo *GenerateInitInstance();
      static void TrkPoint_Dictionary();

      // Function generating the singleton type initializer
      inline ::ROOT::TGenericClassInfo *GenerateInitInstance()
      {
         static ::ROOT::TGenericClassInfo 
            instance("TrkPoint", 0 /*version*/, "./include/../include/LBNEDataNtp_t.hh", 25,
                     ::ROOT::DefineBehavior((void*)0,(void*)0),
                     &TrkPoint_Dictionary, 0);
         return &instance;
      }
      // Insure that the inline function is _not_ optimized away by the compiler
      ::ROOT::TGenericClassInfo *(*_R__UNIQUE_(InitFunctionKeeper))() = &GenerateInitInstance;  
      // Static variable to force the class initialization
      static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstance(); R__UseDummy(_R__UNIQUE_(Init));

      // Dictionary for non-ClassDef classes
      static void TrkPoint_Dictionary() {
         GenerateInitInstance()->GetClass();
      }

   }
}

namespace ROOT {
   void LBNEDataNtp_t_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_LBNEDataNtp_t(void *p = 0);
   static void *newArray_LBNEDataNtp_t(Long_t size, void *p);
   static void delete_LBNEDataNtp_t(void *p);
   static void deleteArray_LBNEDataNtp_t(void *p);
   static void destruct_LBNEDataNtp_t(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::LBNEDataNtp_t*)
   {
      ::LBNEDataNtp_t *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::LBNEDataNtp_t >(0);
      static ::ROOT::TGenericClassInfo 
         instance("LBNEDataNtp_t", ::LBNEDataNtp_t::Class_Version(), "./include/../include/LBNEDataNtp_t.hh", 60,
                  typeid(::LBNEDataNtp_t), DefineBehavior(ptr, ptr),
                  &::LBNEDataNtp_t::Dictionary, isa_proxy, 4,
                  sizeof(::LBNEDataNtp_t) );
      instance.SetNew(&new_LBNEDataNtp_t);
      instance.SetNewArray(&newArray_LBNEDataNtp_t);
      instance.SetDelete(&delete_LBNEDataNtp_t);
      instance.SetDeleteArray(&deleteArray_LBNEDataNtp_t);
      instance.SetDestructor(&destruct_LBNEDataNtp_t);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::LBNEDataNtp_t*)
   {
      return GenerateInitInstanceLocal((::LBNEDataNtp_t*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::LBNEDataNtp_t*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *TrackPoint_t::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *TrackPoint_t::Class_Name()
{
   return "TrackPoint_t";
}

//______________________________________________________________________________
const char *TrackPoint_t::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TrackPoint_t*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TrackPoint_t::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TrackPoint_t*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TrackPoint_t::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TrackPoint_t*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TrackPoint_t::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TrackPoint_t*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
TClass *LBNEDataNtp_t::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *LBNEDataNtp_t::Class_Name()
{
   return "LBNEDataNtp_t";
}

//______________________________________________________________________________
const char *LBNEDataNtp_t::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::LBNEDataNtp_t*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int LBNEDataNtp_t::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::LBNEDataNtp_t*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void LBNEDataNtp_t::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::LBNEDataNtp_t*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *LBNEDataNtp_t::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::LBNEDataNtp_t*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void TrackPoint_t::Streamer(TBuffer &R__b)
{
   // Stream an object of class TrackPoint_t.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(TrackPoint_t::Class(),this);
   } else {
      R__b.WriteClassBuffer(TrackPoint_t::Class(),this);
   }
}

//______________________________________________________________________________
void TrackPoint_t::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class TrackPoint_t.
      TClass *R__cl = ::TrackPoint_t::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "type", &type);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "trkid", &trkid);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "gen", &gen);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "impwt", &impwt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "x", &x);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "y", &y);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "z", &z);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "px", &px);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "py", &py);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "pz", &pz);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_TrackPoint_t(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::TrackPoint_t : new ::TrackPoint_t;
   }
   static void *newArray_TrackPoint_t(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::TrackPoint_t[nElements] : new ::TrackPoint_t[nElements];
   }
   // Wrapper around operator delete
   static void delete_TrackPoint_t(void *p) {
      delete ((::TrackPoint_t*)p);
   }
   static void deleteArray_TrackPoint_t(void *p) {
      delete [] ((::TrackPoint_t*)p);
   }
   static void destruct_TrackPoint_t(void *p) {
      typedef ::TrackPoint_t current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::TrackPoint_t

//______________________________________________________________________________
void LBNEDataNtp_t::Streamer(TBuffer &R__b)
{
   // Stream an object of class LBNEDataNtp_t.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(LBNEDataNtp_t::Class(),this);
   } else {
      R__b.WriteClassBuffer(LBNEDataNtp_t::Class(),this);
   }
}

//______________________________________________________________________________
void LBNEDataNtp_t::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class LBNEDataNtp_t.
      TClass *R__cl = ::LBNEDataNtp_t::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "run", &run);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "evtno", &evtno);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "protonN", &protonN);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "beamHWidth", &beamHWidth);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "beamVWidth", &beamVWidth);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "beamX", &beamX);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "beamY", &beamY);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "protonX", &protonX);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "protonY", &protonY);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "protonZ", &protonZ);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "protonPx", &protonPx);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "protonPy", &protonPy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "protonPz", &protonPz);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nuTarZ", &nuTarZ);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "hornCurrent", &hornCurrent);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Ndxdz", &Ndxdz);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Ndydz", &Ndydz);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Npz", &Npz);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Nenergy", &Nenergy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "NdxdzNear[5]", NdxdzNear);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "NdydzNear[5]", NdydzNear);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "NenergyN[5]", NenergyN);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "NWtNear[5]", NWtNear);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "NdxdzFar[3]", NdxdzFar);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "NdydzFar[3]", NdydzFar);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "NenergyF[3]", NenergyF);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "NWtFar[3]", NWtFar);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Norig", &Norig);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Ndecay", &Ndecay);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Ntype", &Ntype);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Vx", &Vx);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Vy", &Vy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Vz", &Vz);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "pdPx", &pdPx);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "pdPy", &pdPy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "pdPz", &pdPz);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ppdxdz", &ppdxdz);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ppdydz", &ppdydz);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "pppz", &pppz);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ppenergy", &ppenergy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ppmedium", &ppmedium);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ptype", &ptype);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ptrkid", &ptrkid);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ppvx", &ppvx);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ppvy", &ppvy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ppvz", &ppvz);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "muparpx", &muparpx);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "muparpy", &muparpy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "muparpz", &muparpz);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mupare", &mupare);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Necm", &Necm);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Nimpwt", &Nimpwt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "xpoint", &xpoint);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ypoint", &ypoint);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "zpoint", &zpoint);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tvx", &tvx);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tvy", &tvy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tvz", &tvz);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tpx", &tpx);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tpy", &tpy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tpz", &tpz);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tptype", &tptype);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tgen", &tgen);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tptrkid", &tptrkid);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fTrkPtMap", (void*)&fTrkPtMap);
      R__insp.InspectMember("LBNEDataNtp_t::TrkPtMap", (void*)&fTrkPtMap, "fTrkPtMap.", false);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_LBNEDataNtp_t(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::LBNEDataNtp_t : new ::LBNEDataNtp_t;
   }
   static void *newArray_LBNEDataNtp_t(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::LBNEDataNtp_t[nElements] : new ::LBNEDataNtp_t[nElements];
   }
   // Wrapper around operator delete
   static void delete_LBNEDataNtp_t(void *p) {
      delete ((::LBNEDataNtp_t*)p);
   }
   static void deleteArray_LBNEDataNtp_t(void *p) {
      delete [] ((::LBNEDataNtp_t*)p);
   }
   static void destruct_LBNEDataNtp_t(void *p) {
      typedef ::LBNEDataNtp_t current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::LBNEDataNtp_t

namespace ROOT {
   void maplEintcOTrackPoint_tgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void maplEintcOTrackPoint_tgR_Dictionary();
   static void *new_maplEintcOTrackPoint_tgR(void *p = 0);
   static void *newArray_maplEintcOTrackPoint_tgR(Long_t size, void *p);
   static void delete_maplEintcOTrackPoint_tgR(void *p);
   static void deleteArray_maplEintcOTrackPoint_tgR(void *p);
   static void destruct_maplEintcOTrackPoint_tgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const map<int,TrackPoint_t>*)
   {
      map<int,TrackPoint_t> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<int,TrackPoint_t>),0);
      static ::ROOT::TGenericClassInfo 
         instance("map<int,TrackPoint_t>", -2, "prec_stl/map", 63,
                  typeid(map<int,TrackPoint_t>), DefineBehavior(ptr, ptr),
                  0, &maplEintcOTrackPoint_tgR_Dictionary, isa_proxy, 0,
                  sizeof(map<int,TrackPoint_t>) );
      instance.SetNew(&new_maplEintcOTrackPoint_tgR);
      instance.SetNewArray(&newArray_maplEintcOTrackPoint_tgR);
      instance.SetDelete(&delete_maplEintcOTrackPoint_tgR);
      instance.SetDeleteArray(&deleteArray_maplEintcOTrackPoint_tgR);
      instance.SetDestructor(&destruct_maplEintcOTrackPoint_tgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::MapInsert< map<int,TrackPoint_t> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const map<int,TrackPoint_t>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void maplEintcOTrackPoint_tgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const map<int,TrackPoint_t>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_maplEintcOTrackPoint_tgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<int,TrackPoint_t> : new map<int,TrackPoint_t>;
   }
   static void *newArray_maplEintcOTrackPoint_tgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<int,TrackPoint_t>[nElements] : new map<int,TrackPoint_t>[nElements];
   }
   // Wrapper around operator delete
   static void delete_maplEintcOTrackPoint_tgR(void *p) {
      delete ((map<int,TrackPoint_t>*)p);
   }
   static void deleteArray_maplEintcOTrackPoint_tgR(void *p) {
      delete [] ((map<int,TrackPoint_t>*)p);
   }
   static void destruct_maplEintcOTrackPoint_tgR(void *p) {
      typedef map<int,TrackPoint_t> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class map<int,TrackPoint_t>

/********************************************************
* ./src/g4lbneCint.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableg4lbneCint();

extern "C" void G__set_cpp_environmentg4lbneCint() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("../include/TrackPoint_t.hh");
  G__add_compiledheader("../include/LBNEDataNtp_t.hh");
  G__cpp_reset_tagtableg4lbneCint();
}
#include <new>
extern "C" int G__cpp_dllrevg4lbneCint() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TrackPoint_t */
static int G__g4lbneCint_439_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TrackPoint_t* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TrackPoint_t[n];
     } else {
       p = new((void*) gvp) TrackPoint_t[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TrackPoint_t;
     } else {
       p = new((void*) gvp) TrackPoint_t;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__g4lbneCintLN_TrackPoint_t));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_439_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TrackPoint_t*) G__getstructoffset())->Print();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_439_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const TrackPoint_t*) G__getstructoffset())->GetParticleType());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_439_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const TrackPoint_t*) G__getstructoffset())->GetTrackID());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_439_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const TrackPoint_t*) G__getstructoffset())->GetGeneration());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_439_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const TrackPoint_t*) G__getstructoffset())->GetImpWeight());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_439_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const TrackPoint_t*) G__getstructoffset())->GetPosition((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_439_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const TrackPoint_t*) G__getstructoffset())->GetPosition(*(string*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_439_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const TrackPoint_t*) G__getstructoffset())->GetMomentum((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_439_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const TrackPoint_t*) G__getstructoffset())->GetMomentum(*(string*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_439_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TrackPoint_t& obj = ((TrackPoint_t*) G__getstructoffset())->operator=(*(TrackPoint_t*) libp->para[0].ref);
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_439_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TrackPoint_t::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_439_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TrackPoint_t::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_439_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TrackPoint_t::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_439_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TrackPoint_t::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_439_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const TrackPoint_t*) G__getstructoffset())->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_439_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TrackPoint_t*) G__getstructoffset())->ShowMembers(*(TMemberInspector*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_439_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TrackPoint_t*) G__getstructoffset())->Streamer(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_439_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TrackPoint_t*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_439_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TrackPoint_t::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_439_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TrackPoint_t::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_439_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TrackPoint_t::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_439_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TrackPoint_t::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__g4lbneCint_439_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   TrackPoint_t* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new TrackPoint_t(*(TrackPoint_t*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__g4lbneCintLN_TrackPoint_t));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TrackPoint_t G__TTrackPoint_t;
static int G__g4lbneCint_439_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TrackPoint_t*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TrackPoint_t*) (soff+(sizeof(TrackPoint_t)*i)))->~G__TTrackPoint_t();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TrackPoint_t*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TrackPoint_t*) (soff))->~G__TTrackPoint_t();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* TrkPoint */
static int G__g4lbneCint_440_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TrkPoint::StringToEnum(*(string*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_440_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TrkPoint::IntToEnum((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_440_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         string* pobj;
         string xobj = TrkPoint::IntToString((int) G__int(libp->para[0]));
         pobj = new string(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_440_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TrkPoint::StringToInt(*(string*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_440_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         string* pobj;
         string xobj = TrkPoint::AsString((TrkPoint::TrkPoint_t) G__int(libp->para[0]));
         pobj = new string(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_440_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         string* pobj;
         string xobj = TrkPoint::AsLabel((TrkPoint::TrkPoint_t) G__int(libp->para[0]));
         pobj = new string(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_440_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TrkPoint::AsInt((TrkPoint::TrkPoint_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_440_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) TrkPoint::Overlap((const TrkPoint::TrkPoint_t) G__int(libp->para[0]), (const TrkPoint::TrkPoint_t) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}


/* LBNEDataNtp_t */
static int G__g4lbneCint_442_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   LBNEDataNtp_t* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new LBNEDataNtp_t[n];
     } else {
       p = new((void*) gvp) LBNEDataNtp_t[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new LBNEDataNtp_t;
     } else {
       p = new((void*) gvp) LBNEDataNtp_t;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__g4lbneCintLN_LBNEDataNtp_t));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_442_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((LBNEDataNtp_t*) G__getstructoffset())->Clear();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_442_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((LBNEDataNtp_t*) G__getstructoffset())->AddTrkPoint((TrkPoint::TrkPoint_t) G__int(libp->para[0]), *(TrackPoint_t*) libp->para[1].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_442_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((LBNEDataNtp_t*) G__getstructoffset())->AddTrkPoint(*(string*) libp->para[0].ref, *(TrackPoint_t*) libp->para[1].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_442_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((LBNEDataNtp_t*) G__getstructoffset())->AddTrkPoint(
(TrkPoint::TrkPoint_t) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]), (int) G__int(libp->para[3])
, (double) G__double(libp->para[4]), (float) G__double(libp->para[5])
, (float) G__double(libp->para[6]), (float) G__double(libp->para[7])
, (float) G__double(libp->para[8]), (float) G__double(libp->para[9])
, (float) G__double(libp->para[10]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_442_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((LBNEDataNtp_t*) G__getstructoffset())->AddTrkPoint(
*(string*) libp->para[0].ref, (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]), (int) G__int(libp->para[3])
, (double) G__double(libp->para[4]), (float) G__double(libp->para[5])
, (float) G__double(libp->para[6]), (float) G__double(libp->para[7])
, (float) G__double(libp->para[8]), (float) G__double(libp->para[9])
, (float) G__double(libp->para[10]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_442_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const LBNEDataNtp_t::TrkPtMap& obj = ((const LBNEDataNtp_t*) G__getstructoffset())->GetTrackPointMap();
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_442_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const LBNEDataNtp_t*) G__getstructoffset())->TrkPtKeyExists((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_442_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TrackPoint_t& obj = ((const LBNEDataNtp_t*) G__getstructoffset())->GetTrkPtAt((int) G__int(libp->para[0]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_442_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const LBNEDataNtp_t*) G__getstructoffset())->GetTrkPtParticleTypeAt((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_442_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const LBNEDataNtp_t*) G__getstructoffset())->GetTrkPtTrackIDAt((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_442_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const LBNEDataNtp_t*) G__getstructoffset())->GetTrkPtGenerationAt((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_442_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const LBNEDataNtp_t*) G__getstructoffset())->GetTrkPtImpWeightAt((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_442_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const LBNEDataNtp_t*) G__getstructoffset())->GetTrkPtPositionAt((int) G__int(libp->para[0]), *(string*) libp->para[1].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_442_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const LBNEDataNtp_t*) G__getstructoffset())->GetTrkPtMomentumAt((int) G__int(libp->para[0]), *(string*) libp->para[1].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_442_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) LBNEDataNtp_t::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_442_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) LBNEDataNtp_t::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_442_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) LBNEDataNtp_t::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_442_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      LBNEDataNtp_t::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_442_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const LBNEDataNtp_t*) G__getstructoffset())->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_442_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((LBNEDataNtp_t*) G__getstructoffset())->ShowMembers(*(TMemberInspector*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_442_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((LBNEDataNtp_t*) G__getstructoffset())->Streamer(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_442_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((LBNEDataNtp_t*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_442_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) LBNEDataNtp_t::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_442_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) LBNEDataNtp_t::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_442_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) LBNEDataNtp_t::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__g4lbneCint_442_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) LBNEDataNtp_t::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__g4lbneCint_442_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   LBNEDataNtp_t* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new LBNEDataNtp_t(*(LBNEDataNtp_t*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__g4lbneCintLN_LBNEDataNtp_t));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef LBNEDataNtp_t G__TLBNEDataNtp_t;
static int G__g4lbneCint_442_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (LBNEDataNtp_t*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((LBNEDataNtp_t*) (soff+(sizeof(LBNEDataNtp_t)*i)))->~G__TLBNEDataNtp_t();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (LBNEDataNtp_t*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((LBNEDataNtp_t*) (soff))->~G__TLBNEDataNtp_t();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__g4lbneCint_442_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   LBNEDataNtp_t* dest = (LBNEDataNtp_t*) G__getstructoffset();
   *dest = *(LBNEDataNtp_t*) libp->para[0].ref;
   const LBNEDataNtp_t& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TrackPoint_t */

/* TrkPoint */

/* LBNEDataNtp_t */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncg4lbneCint {
 public:
  G__Sizep2memfuncg4lbneCint(): p(&G__Sizep2memfuncg4lbneCint::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncg4lbneCint::*p)();
};

size_t G__get_sizep2memfuncg4lbneCint()
{
  G__Sizep2memfuncg4lbneCint a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceg4lbneCint() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableg4lbneCint() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Float_t",102,-1,0,-1);
   G__setnewtype(-1,"Float 4 bytes (float)",0);
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__g4lbneCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__g4lbneCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__g4lbneCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__g4lbneCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__g4lbneCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__g4lbneCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__g4lbneCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__g4lbneCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__g4lbneCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__g4lbneCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__g4lbneCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__g4lbneCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__g4lbneCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__g4lbneCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TrkPoint_t",117,G__get_linked_tagnum(&G__g4lbneCintLN_TrkPointcLcLETrkPoint),0,G__get_linked_tagnum(&G__g4lbneCintLN_TrkPoint));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,TrackPoint_t>",117,G__get_linked_tagnum(&G__g4lbneCintLN_maplEintcOTrackPoint_tcOlesslEintgRcOallocatorlEpairlEconstsPintcOTrackPoint_tgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,TrackPoint_t,less<int> >",117,G__get_linked_tagnum(&G__g4lbneCintLN_maplEintcOTrackPoint_tcOlesslEintgRcOallocatorlEpairlEconstsPintcOTrackPoint_tgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TrkPtMap",117,G__get_linked_tagnum(&G__g4lbneCintLN_maplEintcOTrackPoint_tcOlesslEintgRcOallocatorlEpairlEconstsPintcOTrackPoint_tgRsPgRsPgR),0,G__get_linked_tagnum(&G__g4lbneCintLN_LBNEDataNtp_t));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TrkPtMapIter",117,G__get_linked_tagnum(&G__g4lbneCintLN_maplEintcOTrackPoint_tcOlesslEintgRcOallocatorlEpairlEconstsPintcOTrackPoint_tgRsPgRsPgRcLcLiterator),0,G__get_linked_tagnum(&G__g4lbneCintLN_LBNEDataNtp_t));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TrackPoint_t */
static void G__setup_memvarTrackPoint_t(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__g4lbneCintLN_TrackPoint_t));
   { TrackPoint_t *p; p=(TrackPoint_t*)0x1000; if (p) { }
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->type)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"type=",0,"particle type");
   G__memvar_setup((void*)((long)(&p->trkid)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"trkid=",0,"track ID (unique ID per Event)");
   G__memvar_setup((void*)((long)(&p->gen)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"gen=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->impwt)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"impwt=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->x)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"x=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->y)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"y=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->z)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"z=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->px)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"px=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->py)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"py=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->pz)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"pz=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__g4lbneCintLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* TrkPoint */
static void G__setup_memvarTrkPoint(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__g4lbneCintLN_TrkPoint));
   {
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__g4lbneCintLN_TrkPointcLcLETrkPoint),-1,-2,1,G__FastAllocString(2048).Format("kTarget=%lldLL",(long long)TrkPoint::kTarget).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__g4lbneCintLN_TrkPointcLcLETrkPoint),-1,-2,1,G__FastAllocString(2048).Format("kTargetExit=%lldLL",(long long)TrkPoint::kTargetExit).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__g4lbneCintLN_TrkPointcLcLETrkPoint),-1,-2,1,G__FastAllocString(2048).Format("kTargetEndPlane=%lldLL",(long long)TrkPoint::kTargetEndPlane).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__g4lbneCintLN_TrkPointcLcLETrkPoint),-1,-2,1,G__FastAllocString(2048).Format("kHorn1Enter=%lldLL",(long long)TrkPoint::kHorn1Enter).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__g4lbneCintLN_TrkPointcLcLETrkPoint),-1,-2,1,G__FastAllocString(2048).Format("kHorn1NeckPlane=%lldLL",(long long)TrkPoint::kHorn1NeckPlane).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__g4lbneCintLN_TrkPointcLcLETrkPoint),-1,-2,1,G__FastAllocString(2048).Format("kHorn1Exit=%lldLL",(long long)TrkPoint::kHorn1Exit).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__g4lbneCintLN_TrkPointcLcLETrkPoint),-1,-2,1,G__FastAllocString(2048).Format("kHorn1EndPlane=%lldLL",(long long)TrkPoint::kHorn1EndPlane).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__g4lbneCintLN_TrkPointcLcLETrkPoint),-1,-2,1,G__FastAllocString(2048).Format("kHorn2Enter=%lldLL",(long long)TrkPoint::kHorn2Enter).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__g4lbneCintLN_TrkPointcLcLETrkPoint),-1,-2,1,G__FastAllocString(2048).Format("kHorn2NeckPlane=%lldLL",(long long)TrkPoint::kHorn2NeckPlane).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__g4lbneCintLN_TrkPointcLcLETrkPoint),-1,-2,1,G__FastAllocString(2048).Format("kHorn2Exit=%lldLL",(long long)TrkPoint::kHorn2Exit).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__g4lbneCintLN_TrkPointcLcLETrkPoint),-1,-2,1,G__FastAllocString(2048).Format("kHorn2EndPlane=%lldLL",(long long)TrkPoint::kHorn2EndPlane).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__g4lbneCintLN_TrkPointcLcLETrkPoint),-1,-2,1,G__FastAllocString(2048).Format("kDPipeEnter=%lldLL",(long long)TrkPoint::kDPipeEnter).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__g4lbneCintLN_TrkPointcLcLETrkPoint),-1,-2,1,G__FastAllocString(2048).Format("kDPipeExit=%lldLL",(long long)TrkPoint::kDPipeExit).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__g4lbneCintLN_TrkPointcLcLETrkPoint),-1,-2,1,G__FastAllocString(2048).Format("kUnknown=%lldLL",(long long)TrkPoint::kUnknown).data(),0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* LBNEDataNtp_t */
static void G__setup_memvarLBNEDataNtp_t(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__g4lbneCintLN_LBNEDataNtp_t));
   { LBNEDataNtp_t *p; p=(LBNEDataNtp_t*)0x1000; if (p) { }
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->run)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"run=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->evtno)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"evtno=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->protonN)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"protonN=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->beamHWidth)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"beamHWidth=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->beamVWidth)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"beamVWidth=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->beamX)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"beamX=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->beamY)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"beamY=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->protonX)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"protonX=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->protonY)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"protonY=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->protonZ)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"protonZ=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->protonPx)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"protonPx=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->protonPy)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"protonPy=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->protonPz)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"protonPz=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nuTarZ)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"nuTarZ=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hornCurrent)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"hornCurrent=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Ndxdz)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Ndxdz=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Ndydz)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Ndydz=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Npz)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Npz=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Nenergy)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Nenergy=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->NdxdzNear)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"NdxdzNear[5]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->NdydzNear)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"NdydzNear[5]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->NenergyN)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"NenergyN[5]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->NWtNear)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"NWtNear[5]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->NdxdzFar)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"NdxdzFar[3]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->NdydzFar)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"NdydzFar[3]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->NenergyF)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"NenergyF[3]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->NWtFar)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"NWtFar[3]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Norig)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Norig=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Ndecay)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Ndecay=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Ntype)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Ntype=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Vx)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Vx=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Vy)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Vy=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Vz)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Vz=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->pdPx)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"pdPx=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->pdPy)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"pdPy=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->pdPz)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"pdPz=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ppdxdz)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"ppdxdz=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ppdydz)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"ppdydz=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->pppz)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"pppz=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ppenergy)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"ppenergy=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ppmedium)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"ppmedium=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ptype)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"ptype=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ptrkid)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"ptrkid=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ppvx)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"ppvx=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ppvy)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"ppvy=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ppvz)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"ppvz=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->muparpx)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"muparpx=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->muparpy)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"muparpy=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->muparpz)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"muparpz=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->mupare)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"mupare=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Necm)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Necm=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Nimpwt)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"Nimpwt=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->xpoint)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"xpoint=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ypoint)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"ypoint=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->zpoint)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"zpoint=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->tvx)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"tvx=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->tvy)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"tvy=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->tvz)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"tvz=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->tpx)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"tpx=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->tpy)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"tpy=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->tpz)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"tpz=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->tptype)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"tptype=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->tgen)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"tgen=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->tptrkid)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"tptrkid=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__g4lbneCintLN_maplEintcOTrackPoint_tcOlesslEintgRcOallocatorlEpairlEconstsPintcOTrackPoint_tgRsPgRsPgR),G__defined_typename("TrkPtMap"),-1,4,"fTrkPtMap=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__g4lbneCintLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarg4lbneCint() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTrackPoint_t(void) {
   /* TrackPoint_t */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__g4lbneCintLN_TrackPoint_t));
   G__memfunc_setup("TrackPoint_t",1234,G__g4lbneCint_439_0_1, 105, G__get_linked_tagnum(&G__g4lbneCintLN_TrackPoint_t), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Print",525,G__g4lbneCint_439_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetParticleType",1526,G__g4lbneCint_439_0_3, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTrackID",930,G__g4lbneCint_439_0_4, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetGeneration",1324,G__g4lbneCint_439_0_5, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetImpWeight",1198,G__g4lbneCint_439_0_6, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPosition",1141,G__g4lbneCint_439_0_7, 102, -1, G__defined_typename("Float_t"), 0, 1, 1, 1, 8, "i - - 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPosition",1141,G__g4lbneCint_439_0_8, 102, -1, G__defined_typename("Float_t"), 0, 1, 1, 1, 8, "u 'string' - 11 - pos", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetMomentum",1138,G__g4lbneCint_439_0_9, 102, -1, G__defined_typename("Float_t"), 0, 1, 1, 1, 8, "i - - 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetMomentum",1138,G__g4lbneCint_439_0_10, 102, -1, G__defined_typename("Float_t"), 0, 1, 1, 1, 8, "u 'string' - 11 - pos", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator=",937,G__g4lbneCint_439_0_11, 117, G__get_linked_tagnum(&G__g4lbneCintLN_TrackPoint_t), -1, 1, 1, 1, 1, 0, "u 'TrackPoint_t' - 11 - rhs", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__g4lbneCint_439_0_12, 85, G__get_linked_tagnum(&G__g4lbneCintLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TrackPoint_t::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__g4lbneCint_439_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TrackPoint_t::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__g4lbneCint_439_0_14, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TrackPoint_t::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__g4lbneCint_439_0_15, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TrackPoint_t::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,G__g4lbneCint_439_0_16, 85, G__get_linked_tagnum(&G__g4lbneCintLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,G__g4lbneCint_439_0_17, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - insp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,G__g4lbneCint_439_0_18, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__g4lbneCint_439_0_19, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__g4lbneCint_439_0_20, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TrackPoint_t::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__g4lbneCint_439_0_21, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TrackPoint_t::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__g4lbneCint_439_0_22, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TrackPoint_t::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__g4lbneCint_439_0_23, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TrackPoint_t::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("TrackPoint_t", 1234, G__g4lbneCint_439_0_24, (int) ('i'), G__get_linked_tagnum(&G__g4lbneCintLN_TrackPoint_t), -1, 0, 1, 1, 1, 0, "u 'TrackPoint_t' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TrackPoint_t", 1360, G__g4lbneCint_439_0_25, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncTrkPoint(void) {
   /* TrkPoint */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__g4lbneCintLN_TrkPoint));
   G__memfunc_setup("StringToEnum",1231,G__g4lbneCint_440_0_1, 105, G__get_linked_tagnum(&G__g4lbneCintLN_TrkPointcLcLETrkPoint), G__defined_typename("TrkPoint::TrkPoint_t"), 0, 1, 1, 1, 0, "u 'string' - 11 - trkpt", (char*)NULL, (void*) G__func2void( (TrkPoint::TrkPoint_t (*)(const string&))(&TrkPoint::StringToEnum) ), 0);
   G__memfunc_setup("IntToEnum",899,G__g4lbneCint_440_0_2, 105, G__get_linked_tagnum(&G__g4lbneCintLN_TrkPointcLcLETrkPoint), G__defined_typename("TrkPoint::TrkPoint_t"), 0, 1, 1, 1, 0, "i - - 0 - trkpt", (char*)NULL, (void*) G__func2void( (TrkPoint::TrkPoint_t (*)(int))(&TrkPoint::IntToEnum) ), 0);
   G__memfunc_setup("IntToString",1125,G__g4lbneCint_440_0_3, 117, G__get_linked_tagnum(&G__g4lbneCintLN_string), -1, 0, 1, 1, 1, 0, "i - - 0 - trkpt", (char*)NULL, (void*) G__func2void( (string (*)(int))(&TrkPoint::IntToString) ), 0);
   G__memfunc_setup("StringToInt",1125,G__g4lbneCint_440_0_4, 105, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 11 - trkpt", (char*)NULL, (void*) G__func2void( (int (*)(const string&))(&TrkPoint::StringToInt) ), 0);
   G__memfunc_setup("AsString",811,G__g4lbneCint_440_0_5, 117, G__get_linked_tagnum(&G__g4lbneCintLN_string), -1, 0, 1, 1, 1, 0, "u 'TrkPoint::ETrkPoint' 'TrkPoint::TrkPoint_t' 0 - trkpt", (char*)NULL, (void*) G__func2void( (string (*)(TrkPoint::TrkPoint_t))(&TrkPoint::AsString) ), 0);
   G__memfunc_setup("AsLabel",660,G__g4lbneCint_440_0_6, 117, G__get_linked_tagnum(&G__g4lbneCintLN_string), -1, 0, 1, 1, 1, 0, "u 'TrkPoint::ETrkPoint' 'TrkPoint::TrkPoint_t' 0 - trkpt", (char*)NULL, (void*) G__func2void( (string (*)(TrkPoint::TrkPoint_t))(&TrkPoint::AsLabel) ), 0);
   G__memfunc_setup("AsInt",479,G__g4lbneCint_440_0_7, 105, -1, -1, 0, 1, 1, 1, 0, "u 'TrkPoint::ETrkPoint' 'TrkPoint::TrkPoint_t' 0 - trkpt", (char*)NULL, (void*) G__func2void( (int (*)(TrkPoint::TrkPoint_t))(&TrkPoint::AsInt) ), 0);
   G__memfunc_setup("Overlap",729,G__g4lbneCint_440_0_8, 103, -1, -1, 0, 2, 1, 1, 0, 
"u 'TrkPoint::ETrkPoint' 'TrkPoint::TrkPoint_t' 10 - lhs u 'TrkPoint::ETrkPoint' 'TrkPoint::TrkPoint_t' 10 - rhs", (char*)NULL, (void*) G__func2void( (bool (*)(const TrkPoint::TrkPoint_t, const TrkPoint::TrkPoint_t))(&TrkPoint::Overlap) ), 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncLBNEDataNtp_t(void) {
   /* LBNEDataNtp_t */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__g4lbneCintLN_LBNEDataNtp_t));
   G__memfunc_setup("LBNEDataNtp_t",1184,G__g4lbneCint_442_0_1, 105, G__get_linked_tagnum(&G__g4lbneCintLN_LBNEDataNtp_t), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Clear",487,G__g4lbneCint_442_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddTrkPoint",1092,G__g4lbneCint_442_0_3, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TrkPoint::ETrkPoint' 'TrkPoint::TrkPoint_t' 0 - trkpt u 'TrackPoint_t' - 1 - tp", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddTrkPoint",1092,G__g4lbneCint_442_0_4, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'string' - 1 - strkpt u 'TrackPoint_t' - 1 - tp", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddTrkPoint",1092,G__g4lbneCint_442_0_5, 121, -1, -1, 0, 11, 1, 1, 0, 
"u 'TrkPoint::ETrkPoint' 'TrkPoint::TrkPoint_t' 0 - trkpt i - - 0 - type "
"i - - 0 - trkid i - - 0 - gen "
"d - - 0 - impwt f - - 0 - x "
"f - - 0 - y f - - 0 - z "
"f - - 0 - px f - - 0 - py "
"f - - 0 - pz", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddTrkPoint",1092,G__g4lbneCint_442_0_6, 121, -1, -1, 0, 11, 1, 1, 0, 
"u 'string' - 1 - strkpt i - - 0 - type "
"i - - 0 - trkid i - - 0 - gen "
"d - - 0 - impwt f - - 0 - x "
"f - - 0 - y f - - 0 - z "
"f - - 0 - px f - - 0 - py "
"f - - 0 - pz", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTrackPointMap",1597,G__g4lbneCint_442_0_7, 117, G__get_linked_tagnum(&G__g4lbneCintLN_maplEintcOTrackPoint_tcOlesslEintgRcOallocatorlEpairlEconstsPintcOTrackPoint_tgRsPgRsPgR), G__defined_typename("LBNEDataNtp_t::TrkPtMap"), 1, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TrkPtKeyExists",1438,G__g4lbneCint_442_0_8, 103, -1, -1, 0, 1, 1, 1, 8, "i - - 0 - key", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTrkPtAt",970,G__g4lbneCint_442_0_9, 117, G__get_linked_tagnum(&G__g4lbneCintLN_TrackPoint_t), -1, 1, 1, 1, 1, 9, "i - - 0 - key", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTrkPtParticleTypeAt",2208,G__g4lbneCint_442_0_10, 105, -1, -1, 0, 1, 1, 1, 8, "i - - 0 - key", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTrkPtTrackIDAt",1612,G__g4lbneCint_442_0_11, 105, -1, -1, 0, 1, 1, 1, 8, "i - - 0 - key", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTrkPtGenerationAt",2006,G__g4lbneCint_442_0_12, 105, -1, -1, 0, 1, 1, 1, 8, "i - - 0 - key", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTrkPtImpWeightAt",1880,G__g4lbneCint_442_0_13, 100, -1, -1, 0, 1, 1, 1, 8, "i - - 0 - key", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTrkPtPositionAt",1823,G__g4lbneCint_442_0_14, 102, -1, -1, 0, 2, 1, 1, 8, 
"i - - 0 - key u 'string' - 11 - pos", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTrkPtMomentumAt",1820,G__g4lbneCint_442_0_15, 102, -1, -1, 0, 2, 1, 1, 8, 
"i - - 0 - key u 'string' - 11 - mpos", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__g4lbneCint_442_0_16, 85, G__get_linked_tagnum(&G__g4lbneCintLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&LBNEDataNtp_t::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__g4lbneCint_442_0_17, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&LBNEDataNtp_t::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__g4lbneCint_442_0_18, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&LBNEDataNtp_t::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__g4lbneCint_442_0_19, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&LBNEDataNtp_t::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,G__g4lbneCint_442_0_20, 85, G__get_linked_tagnum(&G__g4lbneCintLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,G__g4lbneCint_442_0_21, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - insp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,G__g4lbneCint_442_0_22, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__g4lbneCint_442_0_23, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__g4lbneCint_442_0_24, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&LBNEDataNtp_t::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__g4lbneCint_442_0_25, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&LBNEDataNtp_t::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__g4lbneCint_442_0_26, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&LBNEDataNtp_t::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__g4lbneCint_442_0_27, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&LBNEDataNtp_t::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("LBNEDataNtp_t", 1184, G__g4lbneCint_442_0_28, (int) ('i'), G__get_linked_tagnum(&G__g4lbneCintLN_LBNEDataNtp_t), -1, 0, 1, 1, 1, 0, "u 'LBNEDataNtp_t' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~LBNEDataNtp_t", 1310, G__g4lbneCint_442_0_29, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__g4lbneCint_442_0_30, (int) ('u'), G__get_linked_tagnum(&G__g4lbneCintLN_LBNEDataNtp_t), -1, 1, 1, 1, 1, 0, "u 'LBNEDataNtp_t' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncg4lbneCint() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalg4lbneCint() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcg4lbneCint() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__g4lbneCintLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__g4lbneCintLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__g4lbneCintLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__g4lbneCintLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__g4lbneCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__g4lbneCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__g4lbneCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__g4lbneCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__g4lbneCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__g4lbneCintLN_TrackPoint_t = { "TrackPoint_t" , 99 , -1 };
G__linked_taginfo G__g4lbneCintLN_TrkPoint = { "TrkPoint" , 110 , -1 };
G__linked_taginfo G__g4lbneCintLN_TrkPointcLcLETrkPoint = { "TrkPoint::ETrkPoint" , 101 , -1 };
G__linked_taginfo G__g4lbneCintLN_LBNEDataNtp_t = { "LBNEDataNtp_t" , 99 , -1 };
G__linked_taginfo G__g4lbneCintLN_maplEintcOTrackPoint_tcOlesslEintgRcOallocatorlEpairlEconstsPintcOTrackPoint_tgRsPgRsPgR = { "map<int,TrackPoint_t,less<int>,allocator<pair<const int,TrackPoint_t> > >" , 99 , -1 };
G__linked_taginfo G__g4lbneCintLN_maplEintcOTrackPoint_tcOlesslEintgRcOallocatorlEpairlEconstsPintcOTrackPoint_tgRsPgRsPgRcLcLiterator = { "map<int,TrackPoint_t,less<int>,allocator<pair<const int,TrackPoint_t> > >::iterator" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableg4lbneCint() {
  G__g4lbneCintLN_TClass.tagnum = -1 ;
  G__g4lbneCintLN_TBuffer.tagnum = -1 ;
  G__g4lbneCintLN_TMemberInspector.tagnum = -1 ;
  G__g4lbneCintLN_string.tagnum = -1 ;
  G__g4lbneCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__g4lbneCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__g4lbneCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__g4lbneCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__g4lbneCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__g4lbneCintLN_TrackPoint_t.tagnum = -1 ;
  G__g4lbneCintLN_TrkPoint.tagnum = -1 ;
  G__g4lbneCintLN_TrkPointcLcLETrkPoint.tagnum = -1 ;
  G__g4lbneCintLN_LBNEDataNtp_t.tagnum = -1 ;
  G__g4lbneCintLN_maplEintcOTrackPoint_tcOlesslEintgRcOallocatorlEpairlEconstsPintcOTrackPoint_tgRsPgRsPgR.tagnum = -1 ;
  G__g4lbneCintLN_maplEintcOTrackPoint_tcOlesslEintgRcOallocatorlEpairlEconstsPintcOTrackPoint_tgRsPgRsPgRcLcLiterator.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableg4lbneCint() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__g4lbneCintLN_TClass);
   G__get_linked_tagnum_fwd(&G__g4lbneCintLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__g4lbneCintLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__g4lbneCintLN_string);
   G__get_linked_tagnum_fwd(&G__g4lbneCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__g4lbneCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__g4lbneCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__g4lbneCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__g4lbneCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__g4lbneCintLN_TrackPoint_t),sizeof(TrackPoint_t),-1,265472,(char*)NULL,G__setup_memvarTrackPoint_t,G__setup_memfuncTrackPoint_t);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__g4lbneCintLN_TrkPoint),0,-1,0,(char*)NULL,G__setup_memvarTrkPoint,G__setup_memfuncTrkPoint);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__g4lbneCintLN_TrkPointcLcLETrkPoint),sizeof(int),-1,0,(char*)NULL,NULL,NULL);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__g4lbneCintLN_LBNEDataNtp_t),sizeof(LBNEDataNtp_t),-1,263424,"LBNEDataNtp_t",G__setup_memvarLBNEDataNtp_t,G__setup_memfuncLBNEDataNtp_t);
   G__get_linked_tagnum_fwd(&G__g4lbneCintLN_maplEintcOTrackPoint_tcOlesslEintgRcOallocatorlEpairlEconstsPintcOTrackPoint_tgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__g4lbneCintLN_maplEintcOTrackPoint_tcOlesslEintgRcOallocatorlEpairlEconstsPintcOTrackPoint_tgRsPgRsPgRcLcLiterator);
}
extern "C" void G__cpp_setupg4lbneCint(void) {
  G__check_setup_version(30051515,"G__cpp_setupg4lbneCint()");
  G__set_cpp_environmentg4lbneCint();
  G__cpp_setup_tagtableg4lbneCint();

  G__cpp_setup_inheritanceg4lbneCint();

  G__cpp_setup_typetableg4lbneCint();

  G__cpp_setup_memvarg4lbneCint();

  G__cpp_setup_memfuncg4lbneCint();
  G__cpp_setup_globalg4lbneCint();
  G__cpp_setup_funcg4lbneCint();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncg4lbneCint();
  return;
}
class G__cpp_setup_initg4lbneCint {
  public:
    G__cpp_setup_initg4lbneCint() { G__add_setup_func("g4lbneCint",(G__incsetup)(&G__cpp_setupg4lbneCint)); G__call_setup_funcs(); }
   ~G__cpp_setup_initg4lbneCint() { G__remove_setup_func("g4lbneCint"); }
};
G__cpp_setup_initg4lbneCint G__cpp_setup_initializerg4lbneCint;

